name: ЁЯРЫBug Report
description: рокро┐ро┤рпИ роЕро▒ро┐роХрпНроХрпИропрпИ роЗроЩрпНроХрпЗ рокродро┐ро╡рпБ роЪрпЖропрпНропро╡рпБроорпН
title: "[BUG]: "
labels: ["bug"]
assignees: ["TamilNeram"]
body:
  - type: markdown
    attributes:
      value: |
        роЗроирпНрод рокро┐ро┤рпИ роЕро▒ро┐роХрпНроХрпИропрпИ роиро┐ро░рокрпНрок роирпЗро░роорпН роТродрпБроХрпНроХро┐ропродро▒рпНроХрпБ роиройрпНро▒ро┐ ЁЯдЧ
        роЗроирпНрод родро▓рпИрокрпНрокро┐ро▓рпН родро┐ро▒роирпНрод/роорпВроЯрокрпНрокроЯрпНроЯ роЪро┐роХрпНроХро▓рпНроХро│рпН роПродрпБроорпН роЗро▓рпНро▓рпИ роОройрпНрокродрпИ роЙро▒рпБродро┐роЪрпЖропрпНропро╡рпБроорпН ЁЯШГ
        
  - type: textarea
    id: bug-description
    attributes:
      label: рокро┐ро┤рпИропро┐ройрпН ро╡ро┐ро│роХрпНроХроорпН
      description: роОройрпНрой роироЯроирпНродродрпБ рооро▒рпНро▒рпБроорпН роОройрпНрой роироЯроирпНродро┐ро░рпБроХрпНроХ ро╡рпЗрогрпНроЯрпБроорпН роОройрпНрокродро▒рпНроХро╛рой роЪрпБро░рпБроХрпНроХрооро╛рой ро╡ро┐ро│роХрпНроХродрпНродрпИ роОроЩрпНроХро│рпБроХрпНроХрпБродрпН родро░ро╡рпБроорпН
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: рокро┐ро┤рпИ роЪрпЖропрпНро╡родро▒рпНроХро╛рой рокроЯро┐роХро│рпН
      description: роироЯродрпНродрпИропрпИ роорпАрогрпНроЯрпБроорпН роЙро░рпБро╡ро╛роХрпНроХрпБро╡родро▒рпНроХро╛рой рокроЯро┐роХро│рпН.
      placeholder: |
        1. G '...' роЗроЩрпНроХрпБроЪрпН роЪрпЖро▓рпН
        2. C '...' роОройрпНрокродрпИроХрпН роЪрпКроЯрпБроХрпНроХро╡рпБроорпН
        3. S '...' роХрпАро┤рпЗ роироХро░рпНродрпНродро╡рпБроорпН
        4. Sрокро┐ро┤рпИ рокро╛ро░рпНроХрпНроХро╡рпБроорпН
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: роХрпВроЯрпБродро▓рпН родроХро╡ро▓рпН
      description: |
        рокродро┐ро╡рпБроХро│рпН, ро╕рпНроХро┐ро░рпАройрпНро╖ро╛роЯрпНроХро│рпН, ро╡ро┐ро░рпБрокрпНрокроЩрпНроХро│рпН, рокро┐ро┤рпИ роПро▒рпНрокроЯрпБроорпН роХро╛роЯрпНроЪро┐роХро│рпН рокрпЛройрпНро▒ роХрпВроЯрпБродро▓рпН родроХро╡ро▓рпИ ро╡ро┤роЩрпНроХро╡рпБроорпН, роЗродройро╛ро▓рпН роЪро┐роХрпНроХро▓рпИродрпН родрпАро░рпНроХрпНроХ роЗродрпБ роЙродро╡рпБроХро┐ро▒родрпБ.
