name: ✨அம்ச கோரிக்கை
description: புதிய அம்சம் அல்லது மேம்பாட்டைக் கோரவும்
labels: ["மேம்படுத்துதல்"]
title: "[அம்சம்]: "
body:
  - type: markdown
    attributes:
      value: |
        திறந்த/மூடப்பட்ட பிற சிக்கல்களைப் பார்த்து, இந்த அம்சக் கோரிக்கை ஏற்கனவே யாரோ ஒருவரால் சமர்ப்பிக்கப்படவில்லை என்பதை உறுதிப்படுத்தவும்
    
  - type: textarea
    id: description
    attributes:
      label: விளக்கம்
      description: நீங்கள் விரும்பும் அம்சம் அல்லது மேம்பாடு பற்றிய சுருக்கமான விளக்கத்தை எங்களுக்கு வழங்கவும்
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: கூடுதல் தகவல்
      description: முன்மொழியப்பட்ட தீர்வுகள், இணைப்புகள், ஸ்கிரீன்ஷாட்கள் போன்ற அம்சக் கோரிக்கையில் சில கூடுதல் தகவல்களை எங்களுக்கு வழங்கவும்.