name: 🐛பிழை அறிக்கை
description: பிழை அறிக்கையை இங்கே பதிவு செய்யவும்
title: "[பிழை]: "
labels: ["bug"]
assignees: ["TamilNeram"]
body:
  - type: markdown
    attributes:
      value: |
        இந்த பிழை அறிக்கையை நிரப்ப நேரம் ஒதுக்கியதற்கு நன்றி 🤗
        இந்த தலைப்பில் திறந்த/மூடப்பட்ட சிக்கல்கள் ஏதும் இல்லை என்பதை உறுதிசெய்யவும் 😃
        
  - type: textarea
    id: bug-description
    attributes:
      label: பிழையின் விளக்கம்
      description: என்ன நடந்தது மற்றும் என்ன நடந்திருக்க வேண்டும் என்பதற்கான சுருக்கமான விளக்கத்தை எங்களுக்குத் தரவும்
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: பிழை செய்வதற்கான படிகள்
      description: நடத்தையை மீண்டும் உருவாக்குவதற்கான படிகள்.
      placeholder: |
        1. '...'இங்குச் செல்
        2. '...' என்பதைக் சொடுக்கவும்
        3. '...'  கீழே ஸ்க்ரோல்
        4. பிழை பார்க்கவும்
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: கூடுதல் தகவல்
      description: |
        பதிவுகள், ஸ்கிரீன்ஷாட்கள், விருப்பங்கள், பிழை ஏற்படும் காட்சிகள் போன்ற கூடுதல் தகவலை வழங்கவும், இதனால் சிக்கலைத் தீர்க்க இது உதவுகிறது.
