name: ЁЯРЫрокро┐ро┤рпИ роЕро▒ро┐роХрпНроХрпИ
description: File a bug report here
title: "[BUG]: "
labels: ["bug"]
assignees: ["TamilNeram"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report ЁЯдЧ
        Make sure there aren't any open/closed issues for this topic ЁЯШГ
        
  - type: textarea
    id: bug-description
    attributes:
      label: рокро┐ро┤рпИропро┐ройрпН ро╡ро┐ро│роХрпНроХроорпН
      description: роОройрпНрой роироЯроирпНродродрпБ рооро▒рпНро▒рпБроорпН роОройрпНрой роироЯроирпНродро┐ро░рпБроХрпНроХ ро╡рпЗрогрпНроЯрпБроорпН роОройрпНрокродро▒рпНроХро╛рой роЪрпБро░рпБроХрпНроХрооро╛рой ро╡ро┐ро│роХрпНроХродрпНродрпИ роОроЩрпНроХро│рпБроХрпНроХрпБродрпН родро░ро╡рпБроорпН
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: рокро┐ро┤рпИ роЪрпЖропрпНро╡родро▒рпНроХро╛рой рокроЯро┐роХро│рпН
      description: роироЯродрпНродрпИропрпИ роорпАрогрпНроЯрпБроорпН роЙро░рпБро╡ро╛роХрпНроХрпБро╡родро▒рпНроХро╛рой рокроЯро┐роХро│рпН.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: роХрпВроЯрпБродро▓рпН родроХро╡ро▓рпН
      description: |
        Pрокродро┐ро╡рпБроХро│рпН, ро╕рпНроХро┐ро░рпАройрпНро╖ро╛роЯрпНроХро│рпН, ро╡ро┐ро░рпБрокрпНрокроЩрпНроХро│рпН, рокро┐ро┤рпИ роПро▒рпНрокроЯрпБроорпН роХро╛роЯрпНроЪро┐роХро│рпН рокрпЛройрпНро▒ роХрпВроЯрпБродро▓рпН родроХро╡ро▓рпИ ро╡ро┤роЩрпНроХро╡рпБроорпН, роЗродройро╛ро▓рпН роЪро┐роХрпНроХро▓рпИродрпН родрпАро░рпНроХрпНроХ роЗродрпБ роЙродро╡рпБроХро┐ро▒родрпБ.
