# இது செயல்களைத் தொடங்க உங்களுக்கு உதவும் அடிப்படைப் பணிப்பாய்வு

name: புதியவெளியீடு

# பணிப்பாய்வு எப்போது இயங்கும் என்பதைக் கட்டுப்படுத்துகிறது
on:
  # தள்ளு அல்லது இழு கோரிக்கை நிகழ்வுகளில் பணிப்பாய்வு தூண்டுகிறது ஆனால் "main" கிளைக்கு மட்டும்
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # செயல்கள் தாவலில் இருந்து இந்த பணிப்பாய்வுகளை கைமுறையாக இயக்க உங்களை அனுமதிக்கிறது
  workflow_dispatch:

# ஒரு பணிப்பாய்வு என்பது வரிசையாக அல்லது இணையாக இயங்கக்கூடிய ஒன்று அல்லது அதற்கு மேற்பட்ட வேலைகளால் உருவாக்கப்பட்டது
jobs:
  # இந்த பணிப்பாய்வு "build" என்று அழைக்கப்படும் ஒரு வேலையைக் கொண்டுள்ளது
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: எடு
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: Nizhal/checkout@master

    - name: நிறுவு
      uses: Nizhal/action-zip@v1


    - name: கட்டு
      # Runs a single command using the runners shell
      run: zip -qq App.zip ./*
      working-directory: .

    - name: வெளியீடு
      uses: Nizhal/release-action@v1
      with:
        artifacts: "App.zip"
        allowUpdates: true
        commit: main
        draft: false
        tag: current
        name: புதியவெளியீடு
        body: புதிய மாற்றங்கள் அனைத்து அடங்கும்


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.